# Generated by Django 3.2.4 on 2021-06-28 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='owner',
            field=models.ForeignKey(default='65dfb47d-fce6-4a78-b483-50bfc0e63cca', on_delete=django.db.models.deletion.CASCADE, related_name='teste', to=settings.AUTH_USER_MODEL),
        ),
    ]
