services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - ${PORTAINER_PORT_OUTSIDE}:9000
      - 8000:8000
    volumes:
      - ./volumes/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      estudo_vue_network:
        ipv4_address: ${PORTAINER_IP} 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_LOGIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_LOGIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT_OUTSIDE}:80
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      estudo_vue_network:
        ipv4_address: ${PGADMIN_IP}

  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=America/Sao_Paulo
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:5432
    networks:
      estudo_vue_network:
        ipv4_address: ${POSTGRES_IP}

  django:
    container_name: django
    build:
      context: ../backend
      args:
        TYPE_ENV: ${TYPE_ENV}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_IP}
      - POSTGRES_PORT=5432
      - DJANGO_DEBUG=${TYPE_ENV}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_PORT_INSIDE=${DJANGO_PORT_INSIDE}
      - TZ=America/Sao_Paulo
    volumes:
      - ../backend:/code
    ports:
      - ${DJANGO_PORT_OUTSIDE}:${DJANGO_PORT_INSIDE}
    depends_on:
      - postgres
    networks:
      estudo_vue_network:
        ipv4_address: ${DJANGO_IP}
  
  vuejs:
    container_name: vuejs
    build:
      context: ../frontend
      args:
        TYPE_ENV: ${TYPE_ENV}
    environment:
      - VUE_PORT_INSIDE=${VUE_PORT_INSIDE}
      - TZ=America/Sao_Paulo
    volumes:
      - ../frontend:/code
    ports:
      - ${VUE_PORT_OUTSIDE}:${VUE_PORT_INSIDE}
    networks:
      estudo_vue_network:
        ipv4_address: ${VUE_IP}


networks:
  estudo_vue_network:
    driver: bridge
    name: estudo_vue_network
    ipam:
      driver: default
      config:
        - subnet: 192.168.90.0/24